version: '3.8'

networks:
  todoapp_net:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - database
    container_name: todoapi_services
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;port=3306;Database=todo-api;Uid=root;Pwd=84880897;
    networks:
      - todoapp_net

  database:
    image: mysql
    container_name: database_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 84880897
      MYSQL_DATABASE: todo-api
    ports:
      - "3306:3306"
    networks:
      - todoapp_net
    volumes:
      - todoapi_data:/var/lib/mysql

volumes:
  todoapi_data:
